my_robot:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50  

    # Position Controllers ---------------------------------------
    joint1_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_front_wheel_joint_position
        pid: {p: 100.0, i: 0.01, d: 10.0}
    joint2_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_back_wheel_joint_position
        pid: {p: 100.0, i: 0.01, d: 10.0}
    joint3_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_front_wheel_joint_position
        pid: {p: 100.0, i: 0.01, d: 10.0}
    joint4_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_back_wheel_joint_position
        pid: {p: 100.0, i: 0.01, d: 10.0}
