#!/usr/bin/env python

import rospy
from geometry_msgs.msg import Twist
from time import sleep
import time
from std_msgs.msg import String, Duration
import message_filters
from message_filters import TimeSynchronizer, Subscriber, Cache

def part():
	pub = rospy.Publisher('/my_robot/Differential_left_controller/cmd_vel', Twist, queue_size=5)
	pub2 = rospy.Publisher('/my_robot/Differential_right_controller/cmd_vel', Twist, queue_size=5)

	for i in range(40000):
		msg = Twist()
		msg.linear.x = 0.1
		pub.publish(msg)
		pub2.publish(msg)
		rospy.loginfo('Stage 1')
	for i in range(3500):
		## for turn right
		msg = Twist()
		msg.linear.x = 0.1
		pub.publish(msg)
		msg.linear.x = -0.1
		pub2.publish(msg)
		rospy.loginfo('Turning')
		## for turn left
		##msg.linear.x = -0.1
		##pub.publish(msg)
		##msg.linear.x = 0.1
		##pub2.publish(msg)
		##rospy.loginfo('Turning')
	for i in range(10500):
		msg = Twist()
		msg.linear.x = 0.1
		pub.publish(msg)
		pub2.publish(msg)
		rospy.loginfo('Stage 2')
	for i in range(1000000):
		msg = Twist()
		msg.linear.x = 0
		pub.publish(msg)
		pub2.publish(msg)
		rospy.loginfo('Finish !')

if __name__ == '__main__':

		rospy.init_node('node', anonymous=True)
		part()
		rospy.spin()

